batch_shipyard:
  storage_account_settings: afterburnerstorage
global_resources:
  docker_images:
  - acrafterburner01.azurecr.io/jmeter
  volumes:
    shared_data_volumes:
      azurefile_vol:
        volume_driver: azurefile
        storage_account_settings: afterburnerstorage
        azure_file_share_name: jmeter
        container_path: $AZ_BATCH_NODE_SHARED_DIR/azfile
        mount_options:
        - file_mode=0777
        - dir_mode=0777
        bind_options: rw
