credentials:
  batch:
    account_key: [KEY]
    account_service_url: https://[NAME].westeurope.batch.azure.com
  storage:
    afterburnerstorage:
      account: [ACCOUNT_NAME]
      account_key: [KEY]
      endpoint: core.windows.net
  docker_registry:
    acrafterburner01.azurecr.io:
      username: [USERNAME]
      password: [PASSWORD]

