credentials:
  batch:
    account_key: [BATCH_ACCOUNT_KEY]
    account_service_url: https://[BATCH_ACCOUNT_NAME].westeurope.batch.azure.com
  storage:
    jmeterstorageaccount:
      account: [STORAGE_NAME]
      account_key: [STORAGE_KEY]
      endpoint: core.windows.net
  docker_registry:
    [DOCKER_REGISTRY]:
      username: [DOCKER_USER]
      password: [DOCKER_PASSWORD]

