job_specifications:
- id: myjmeterjob
  tasks:
  - environment_variables:
      JMETER_FILES_PATH: jmeter
      JMETER_SCRIPT_NAME: afterburner-simple.jmx
      JMETER_JMX_DOMAIN: appafterburner01.azurewebsites.net
      JMETER_FILE_DIR: /mnt/batch/tasks/mounts/azfile-stokpop-jmeter/run00001
    docker_image: acrafterburner01.azurecr.io/jmeter
    command: -Jjmx.domain=$JMETER_JMX_DOMAIN -n -t $JMETER_FILE_DIR/$JMETER_SCRIPT_NAME -l $JMETER_FILE_DIR/result.jtl -j $JMETER_FILE_DIR/jmeter.log
    