---
# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout afterburner repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set tag name
        run: |
          VERSION=$(cat ./VERSION)
          echo "TAG_NAME=$VERSION" >> $GITHUB_ENV
      # if no tag exists, this is expected to fail
      - name: Switch to git tag for release
        if: contains(env.TAG_NAME, 'SNAPSHOT') != true
        run: |
          git fetch --all --tags
          git checkout tags/${{ env.TAG_NAME }} -b ${{ env.TAG_NAME }}-tmp-branch
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build local
        run: ./mvnw clean install
      # Build docker image
      - name: Create local docker image
        run: ./mvnw -Pmulti-arch-docker,pyroscope clean package jib:build
      # push to github
      - name: Login docker
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push
