---
name: Get database stats

on:
  workflow_dispatch:
    inputs:

jobs:

  get-database-stats:
    runs-on: self-hosted
    steps:
      - name: Download and install MySql APT repository
        run: |
          wget https://dev.mysql.com/get/mysql-apt-config_0.8.22-1_all.deb;
          sudo dpkg -i mysql-apt-config_0.8.22-1_all.deb;
          sudo apt-get update
      - name: Install mysql cli and msql-shell
        run: sudo apt-get install mysql-apt-config && sudo apt-get install -y mysql-shell mysql-client 
      - name: Install mysql cli and mysql-shell
        uses: actions/checkout@v3
        with:
          repository: 'xdbtime/xdbtime'
      - name: Prepare database scripts
        run: |
          mkdir -p ~/.mysqlsh/init.d;
          cd xdbtime/mysql/init.d;
          cp xdbperformance-status.py ~/.mysqlsh/init.d;
          cd xdbtime/mysql;
      - name: Create perfomance report
        run: |
          echo "report = shell.reports.performance(shell.getSession())" | root:${{ secrets.AFTERBURNER_DB_PASSWORD }}@afterburner-db-mysql-headless.acme.svc.cluster.local:3306 --js
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: database performance report
          path: /reports/*.html