---
name: Get database stats

on:
  workflow_dispatch:
    inputs:

jobs:

  get-database-stats:
    runs-on: self-hosted
    steps:
      - name: Install mysql cli and msql-shell
        run: sudo apt-get install -y mysql-shell mysql-client 
      - name: Install mysql cli and msql-shell
        uses: actions/checkout@v3
        with:
        repository: 'https://github.com/xdbtime/xdbtime.git'
      - name: Prepare database scripts
        run: |
          mkdir -p ~/.mysqlsh/init.d;
          cd xdbtime/mysql/init.d;
          cp xdbperformance-status.py ~/.mysqlsh/init.d;
          cd xdbtime/mysql;
      - name: Create perfomance report
        run: |
          echo "report = shell.reports.performance(shell.getSession())" | root:${{ secrets.AFTERBURNER_DB_PASSWORD }}@afterburner-db-mysql-headless.acme.svc.cluster.local:3306 --js
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: database performance report
          path: /reports/*.html