---

# make change in demo branch that effects cpu performance
name: Proxy dev

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout afterburner repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: demo
      - name: Make a change
        run: |
          java_file=afterburner-java/src/main/java/io/perfana/afterburner/controller/CpuBurner.java
          if grep -q "some variation: is more fun" "$File"; then
            commit_message = "make cpu more efficient"
            sed -i 's/some variation: is more fun/no variation: is no fun/g' $java_file
            sed -i 's/int funSize = (int) (matrixSize \* (1.0 + (random.nextDouble() \* 3.3)))/int funSize = matrixSize/g' $java_file
          else
            commit_message = "make matrix calculation more variable"
            sed -i 's/no variation: is no fun/some variation: is more fun/g' $java_file
            sed -i 's/int funSize = matrixSize/int funSize = (int) (matrixSize \* (1.0 + (random.nextDouble() \* 3.3)))/g' $java_file
          fi
          echo "commit_message=$commit_message" >> $GITHUB_OUTPUT
      - name: Commit files
        #working-directory: .
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Proxy Developer"
          git commit -m "Proxy Dev: $commit_message" -a
          git push