---

name: Just say hello

on:
  workflow_dispatch:
  schedule:
    # every 5 minutes
    - cron: '5 * * * *'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: dviersel/perfana-action@v0.1-alpha-3
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
