---

# make change in demo branch that effects cpu performance
name: Just say hello

on:
  workflow_dispatch:
  schedule:
    # At minute 10 past hour 8 from 8h to 13h AMS time (6-11 UTC)
    - cron: '10 6-20 * * *'on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: dviersel/perfana-action@v0.1
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
